services:
    app:
        build: .
        networks:
            - backend
        command: python3 app.py
        ports:
            - 8000:8000
networks:
  backend:
    name: backend
    external: true